services:
  mosquitto:
    restart: unless-stopped
    image: eclipse-mosquitto
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - ./services/mosquitto/conf:/mosquitto/config
    logging:
      driver: "json-file"
      options:
        max-size: 10m
        max-file: "1"
        labels: "production_status"
        env: "os"

  agrometeo-simulator:
    build: ./services/agrometeo-simulator-py
    restart: unless-stopped
    environment:
      - BROKER_HOST=${BROKER_HOST}
      - BROKER_PORT=${BROKER_PORT}
      - INTERVAL_SECONDS=${INTERVAL_SECONDS}
      - PYTHONUNBUFFERED=1
    depends_on:
      - mosquitto
    logging:
      driver: "json-file"
      options:
        max-size: 10m
        max-file: "1"
        labels: "production_status"
        env: "os"

  dataseries-db:
    image: timescale/timescaledb:latest-pg16
    restart: always
    ports:
      - 5432:${DATASERIES_DB_PORT}
    environment:
      - POSTGRES_USER=${DATASERIES_DB_USER}
      - POSTGRES_PASSWORD=${DATASERIES_DB_PASSWORD}
    volumes:
      - ./services/persistor/pgdata/data:/home/postgres/pgdata/data

  postgres-admin:
    image: dpage/pgadmin4:8.8
    restart: always
    ports:
      - ${PGADMIN_PORT}:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}

  intercom:
    image: rabbitmq:3-management
    restart: unless-stopped
    ports:
      - '15672:15672'
      - '5671:5671'
      - '5672:5672'
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
      - RABBITMQ_PLUGINS="rabbitmq_management"
    volumes:
      - ./services/intercom/lib/rabbitmq:/var/lib/rabbitmq
      - ./services/intercom/rabbitmq/etc:/etc/rabbitmq
    logging:
      driver: "json-file"
      options:
        max-size: 10m
        max-file: "1"
        labels: "production_status"
        env: "os"
